### ISSUE TITLE
skb being allocated twice

### ISSUE THREAD

**Issue by evertonen** [a-zaki/genl_ex#3]
In function greet_group the skb is being allocated twice. Is this really necessary?

**Comment by a-zaki** [comment]
@evertonen  Please test and send a PR so that I can follow on your suggestions. Thanks.

**Comment by evertonen** [comment]
I tested and a single skb allocation is fine. I will send the change.

**Comment by evertonen** [comment]
Hi, I need push access to send the patch.

**Comment by a-zaki** [comment]
@evertonen No you don't, just fork it first and push to your fork, then send a pull request.

**Comment by evertonen** [comment]
This is odd, I've tested to push to another new repo that I created and it works by https. But when I push to yours it gives me access denied.
Just like that:
remote: Permission to a-zaki/genl_ex.git denied to evertonen.
fatal: unable to access 'https://github.com/a-zaki/genl_ex/': The requested URL returned error: 403

**Comment by a-zaki** [comment]
This is weird, I had other people push to this repo. Did you fork? Your name does not show up in forked list!

**Comment by a-zaki** [comment]
Oh I see now. You do not push to a-zaki/genl_ex, you push to your forked repo and then make the pull request. Again fork first.

**Comment by evertonen** [comment]
Sorry, I've been missing the fork all the way. Now the push worked and the PR is there :)

**Comment by a-zaki** [comment]
Applied, thanks.
